In [1]:
import pandas as pd
df=pd.read_csv("pharma_dataset.csv")

In [2]:
df.head()

,drug_id,drug_name,therapeutic_area,molecule_type,launch_year,region,month_year,units_sold,drug_price,competitor_1_price,...,insurance_coverage,hospital_tier,doctor_visits,marketing_spend,rep_visits,regulatory_flags,adverse_events,patient_income_level,total_revenue,market_share
0,D0103,Immunexa,Oncology,Small Molecule,2010,Europe,01-2021,228,419.81,450.68,...,47,Tier 1,51,131536.21,25,0,7,Low,95716.68,51.47
1,D0180,Diabetrol,Cardiology,Biologic,2020,North America,01-2021,199,376.51,447.60,...,68,Tier 3,63,88988.30,37,0,4,Mid,74925.49,20.52
2,D0093,ArthroAid,Oncology,Biosimilar,2011,LATAM,01-2021,208,426.35,488.72,...,49,Tier 1,40,122973.71,32,0,4,Low,88680.80,37.68
3,D0015,Diabetrol,Pulmonology,Small Molecule,2004,North America,01-2021,180,50.66,356.10,...,73,Tier 3,56,89797.30,29,0,5,Mid,9118.80,32.03
4,D0107,ArthroAid,Diabetes,Biosimilar,2022,LATAM,01-2021,210,35.18,261.10,...,63,Tier 1,51,39069.20,32,2,4,Mid,7387.80,40.23

In [3]:
df.tail()

,drug_id,drug_name,therapeutic_area,molecule_type,launch_year,region,month_year,units_sold,drug_price,competitor_1_price,...,insurance_coverage,hospital_tier,doctor_visits,marketing_spend,rep_visits,regulatory_flags,adverse_events,patient_income_level,total_revenue,market_share
1495,D0181,Dermasol,Diabetes,Biosimilar,2012,APAC,02-2025,194,369.61,53.50,...,50,Tier 2,48,90639.64,32,0,7,Mid,71704.34,51.19
1496,D0036,Diabetrol,Neurology,Biosimilar,2016,North America,02-2025,213,249.49,142.82,...,48,Tier 3,70,31822.65,26,0,5,Low,53141.37,19.47
1497,D0115,Immunexa,Oncology,Biologic,2022,APAC,02-2025,218,262.51,114.47,...,93,Tier 3,54,36338.00,31,0,7,Mid,57227.18,35.80
1498,D0026,Diabetrol,Rheumatology,Biologic,2019,APAC,02-2025,187,428.58,27.63,...,95,Tier 3,51,127312.91,24,0,4,Low,80144.46,34.00
1499,D0029,OncoCure,Pulmonology,Biosimilar,2004,LATAM,02-2025,200,346.85,277.71,...,63,Tier 3,48,125421.55,32,0,1,Mid,69370.00,35.27

In [4]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1495    False
1496    False
1497    False
1498    False
1499    False
Length: 1500, dtype: bool

In [7]:
df.isnull().sum()

drug_id                 0
drug_name               0
therapeutic_area        0
molecule_type           0
launch_year             0
region                  0
month_year              0
units_sold              0
drug_price              0
competitor_1_price      0
competitor_2_price      0
competitor_3_price      0
insurance_coverage      0
hospital_tier           0
doctor_visits           0
marketing_spend         0
rep_visits              0
regulatory_flags        0
adverse_events          0
patient_income_level    0
total_revenue           0
market_share            0
dtype: int64

In [8]:
df.drop_duplicates()

,drug_id,drug_name,therapeutic_area,molecule_type,launch_year,region,month_year,units_sold,drug_price,competitor_1_price,...,insurance_coverage,hospital_tier,doctor_visits,marketing_spend,rep_visits,regulatory_flags,adverse_events,patient_income_level,total_revenue,market_share
0,D0103,Immunexa,Oncology,Small Molecule,2010,Europe,01-2021,228,419.81,450.68,...,47,Tier 1,51,131536.21,25,0,7,Low,95716.68,51.47
1,D0180,Diabetrol,Cardiology,Biologic,2020,North America,01-2021,199,376.51,447.60,...,68,Tier 3,63,88988.30,37,0,4,Mid,74925.49,20.52
2,D0093,ArthroAid,Oncology,Biosimilar,2011,LATAM,01-2021,208,426.35,488.72,...,49,Tier 1,40,122973.71,32,0,4,Low,88680.80,37.68
3,D0015,Diabetrol,Pulmonology,Small Molecule,2004,North America,01-2021,180,50.66,356.10,...,73,Tier 3,56,89797.30,29,0,5,Mid,9118.80,32.03
4,D0107,ArthroAid,Diabetes,Biosimilar,2022,LATAM,01-2021,210,35.18,261.10,...,63,Tier 1,51,39069.20,32,2,4,Mid,7387.80,40.23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,D0181,Dermasol,Diabetes,Biosimilar,2012,APAC,02-2025,194,369.61,53.50,...,50,Tier 2,48,90639.64,32,0,7,Mid,71704.34,51.19
1496,D0036,Diabetrol,Neurology,Biosimilar,2016,North America,02-2025,213,249.49,142.82,...,48,Tier 3,70,31822.65,26,0,5,Low,53141.37,19.47
1497,D0115,Immunexa,Oncology,Biologic,2022,APAC,02-2025,218,262.51,114.47,...,93,Tier 3,54,36338.00,31,0,7,Mid,57227.18,35.80
1498,D0026,Diabetrol,Rheumatology,Biologic,2019,APAC,02-2025,187,428.58,27.63,...,95,Tier 3,51,127312.91,24,0,4,Low,80144.46,34.00
1499,D0029,OncoCure,Pulmonology,Biosimilar,2004,LATAM,02-2025,200,346.85,277.71,...,63,Tier 3,48,125421.55,32,0,1,Mid,69370.00,35.27

In [9]:
df.shape

(1500, 22)

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   drug_id               1500 non-null   str
 1   drug_name             1500 non-null   str
 2   therapeutic_area      1500 non-null   str
 3   molecule_type         1500 non-null   str
 4   launch_year           1500 non-null   int64
 5   region                1500 non-null   str
 6   month_year            1500 non-null   str
 7   units_sold            1500 non-null   int64
 8   drug_price            1500 non-null   float64
 9   competitor_1_price    1500 non-null   float64
 10  competitor_2_price    1500 non-null   float64
 11  competitor_3_price    1500 non-null   float64
 12  insurance_coverage    1500 non-null   int64
 13  hospital_tier         1500 non-null   str
 14  doctor_visits         1500 non-null   int64
 15  marketing_spend       1500 non-null   float64
 16  rep_visits            1500 non-null   int64
 17  regulatory_flags      1500 non-null   int64
 18  adverse_events        1500 non-null   int64
 19  patient_income_level  1500 non-null   str
 20  total_revenue         1500 non-null   float64
 21  market_share          1500 non-null   float64
dtypes: float64(7), int64(7), str(8)
memory usage: 342.0 KB

In [11]:
df.describe()

,launch_year,units_sold,drug_price,competitor_1_price,competitor_2_price,competitor_3_price,insurance_coverage,doctor_visits,marketing_spend,rep_visits,regulatory_flags,adverse_events,total_revenue,market_share
count,1500.000000,1500.00000,1500.000000,1500.000000,1500.000000,1500.0000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000
mean,2011.628667,200.08600,259.208640,255.871213,263.208953,259.8717,68.870667,50.443333,106293.493800,30.134667,0.183333,4.939333,51824.581380,30.695627
std,6.538344,14.42026,136.462937,138.252621,137.701125,138.7295,17.267756,7.107024,55064.928402,5.637409,0.491817,2.181473,27514.872275,12.621137
min,2000.000000,150.00000,20.090000,20.490000,20.060000,20.1200,40.000000,29.000000,10474.140000,12.000000,0.000000,0.000000,3636.290000,14.180000
25%,2006.000000,190.00000,143.980000,141.925000,144.560000,139.1475,54.000000,46.000000,59086.495000,26.000000,0.000000,3.000000,28742.505000,20.527500
50%,2012.000000,200.00000,261.465000,252.115000,268.920000,261.6700,69.000000,50.000000,107260.605000,30.000000,0.000000,5.000000,52104.890000,26.710000
75%,2017.000000,210.00000,373.632500,375.020000,381.447500,377.4225,84.000000,55.000000,154339.465000,34.000000,0.000000,6.000000,74538.962500,37.420000
max,2022.000000,254.00000,499.760000,499.830000,499.560000,499.9500,99.000000,73.000000,199981.190000,54.000000,2.000000,15.000000,109419.750000,67.710000

In [12]:
df.dropna

<bound method DataFrame.dropna of      drug_id  drug_name therapeutic_area   molecule_type  launch_year  \
0      D0103   Immunexa         Oncology  Small Molecule         2010
1      D0180  Diabetrol       Cardiology        Biologic         2020
2      D0093  ArthroAid         Oncology      Biosimilar         2011
3      D0015  Diabetrol      Pulmonology  Small Molecule         2004
4      D0107  ArthroAid         Diabetes      Biosimilar         2022
...      ...        ...              ...             ...          ...
1495   D0181   Dermasol         Diabetes      Biosimilar         2012
1496   D0036  Diabetrol        Neurology      Biosimilar         2016
1497   D0115   Immunexa         Oncology        Biologic         2022
1498   D0026  Diabetrol     Rheumatology        Biologic         2019
1499   D0029   OncoCure      Pulmonology      Biosimilar         2004

             region month_year  units_sold  drug_price  competitor_1_price  \
0            Europe    01-2021         228      419.81              450.68
1     North America    01-2021         199      376.51              447.60
2             LATAM    01-2021         208      426.35              488.72
3     North America    01-2021         180       50.66              356.10
4             LATAM    01-2021         210       35.18              261.10
...             ...        ...         ...         ...                 ...
1495           APAC    02-2025         194      369.61               53.50
1496  North America    02-2025         213      249.49              142.82
1497           APAC    02-2025         218      262.51              114.47
1498           APAC    02-2025         187      428.58               27.63
1499          LATAM    02-2025         200      346.85              277.71

      ...  insurance_coverage  hospital_tier  doctor_visits marketing_spend  \
0     ...                  47         Tier 1             51       131536.21
1     ...                  68         Tier 3             63        88988.30
2     ...                  49         Tier 1             40       122973.71
3     ...                  73         Tier 3             56        89797.30
4     ...                  63         Tier 1             51        39069.20
...   ...                 ...            ...            ...             ...
1495  ...                  50         Tier 2             48        90639.64
1496  ...                  48         Tier 3             70        31822.65
1497  ...                  93         Tier 3             54        36338.00
1498  ...                  95         Tier 3             51       127312.91
1499  ...                  63         Tier 3             48       125421.55

      rep_visits  regulatory_flags  adverse_events  patient_income_level  \
0             25                 0               7                   Low
1             37                 0               4                   Mid
2             32                 0               4                   Low
3             29                 0               5                   Mid
4             32                 2               4                   Mid
...          ...               ...             ...                   ...
1495          32                 0               7                   Mid
1496          26                 0               5                   Low
1497          31                 0               7                   Mid
1498          24                 0               4                   Low
1499          32                 0               1                   Mid

      total_revenue market_share
0          95716.68        51.47
1          74925.49        20.52
2          88680.80        37.68
3           9118.80        32.03
4           7387.80        40.23
...             ...          ...
1495       71704.34        51.19
1496       53141.37        19.47
1497       57227.18        35.80
1498       80144.46        34.00
1499       69370.00        35.27

[1500 rows x 22 columns]>

In [13]:
df.to_csv

<bound method NDFrame.to_csv of      drug_id  drug_name therapeutic_area   molecule_type  launch_year  \
0      D0103   Immunexa         Oncology  Small Molecule         2010
1      D0180  Diabetrol       Cardiology        Biologic         2020
2      D0093  ArthroAid         Oncology      Biosimilar         2011
3      D0015  Diabetrol      Pulmonology  Small Molecule         2004
4      D0107  ArthroAid         Diabetes      Biosimilar         2022
...      ...        ...              ...             ...          ...
1495   D0181   Dermasol         Diabetes      Biosimilar         2012
1496   D0036  Diabetrol        Neurology      Biosimilar         2016
1497   D0115   Immunexa         Oncology        Biologic         2022
1498   D0026  Diabetrol     Rheumatology        Biologic         2019
1499   D0029   OncoCure      Pulmonology      Biosimilar         2004

             region month_year  units_sold  drug_price  competitor_1_price  \
0            Europe    01-2021         228      419.81              450.68
1     North America    01-2021         199      376.51              447.60
2             LATAM    01-2021         208      426.35              488.72
3     North America    01-2021         180       50.66              356.10
4             LATAM    01-2021         210       35.18              261.10
...             ...        ...         ...         ...                 ...
1495           APAC    02-2025         194      369.61               53.50
1496  North America    02-2025         213      249.49              142.82
1497           APAC    02-2025         218      262.51              114.47
1498           APAC    02-2025         187      428.58               27.63
1499          LATAM    02-2025         200      346.85              277.71

      ...  insurance_coverage  hospital_tier  doctor_visits marketing_spend  \
0     ...                  47         Tier 1             51       131536.21
1     ...                  68         Tier 3             63        88988.30
2     ...                  49         Tier 1             40       122973.71
3     ...                  73         Tier 3             56        89797.30
4     ...                  63         Tier 1             51        39069.20
...   ...                 ...            ...            ...             ...
1495  ...                  50         Tier 2             48        90639.64
1496  ...                  48         Tier 3             70        31822.65
1497  ...                  93         Tier 3             54        36338.00
1498  ...                  95         Tier 3             51       127312.91
1499  ...                  63         Tier 3             48       125421.55

      rep_visits  regulatory_flags  adverse_events  patient_income_level  \
0             25                 0               7                   Low
1             37                 0               4                   Mid
2             32                 0               4                   Low
3             29                 0               5                   Mid
4             32                 2               4                   Mid
...          ...               ...             ...                   ...
1495          32                 0               7                   Mid
1496          26                 0               5                   Low
1497          31                 0               7                   Mid
1498          24                 0               4                   Low
1499          32                 0               1                   Mid

      total_revenue market_share
0          95716.68        51.47
1          74925.49        20.52
2          88680.80        37.68
3           9118.80        32.03
4           7387.80        40.23
...             ...          ...
1495       71704.34        51.19
1496       53141.37        19.47
1497       57227.18        35.80
1498       80144.46        34.00
1499       69370.00        35.27

[1500 rows x 22 columns]>